import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import { FunctionComponent, PropsWithChildren } from 'react'
import GlobalStyle from '@/common/GlobalStyle'
import Layout from '@/infrastructure/Layout'

const poppins = Poppins({ weight: '400', subsets: ['latin-ext'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout: FunctionComponent<PropsWithChildren> = ({ children }) => (
  <html lang="pl">
  <GlobalStyle />
    <body className={poppins.className}>
      <Layout>
        {children}
      </Layout>
    </body>
  </html>
)


export default RootLayout
