import './global.sass'

import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import { FunctionComponent, PropsWithChildren } from 'react'
import styles from './layout.module.sass'
import Topbar from '@/infrastructure/Topbar'
import { cookies } from 'next/headers'

const poppins = Poppins({ weight: ['100', '300', '400', '700'], subsets: ['latin-ext'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout: FunctionComponent<PropsWithChildren> = ({ children }) => {
  const client = cookies().get('user')
  console.log(client)
  return (
    <html lang="pl">
    <body className={poppins.className}>
    <main className={styles.wrapper}>
      <Topbar client={client?.value} />
      <div className={styles.content}>
        {children}
      </div>
    </main>
    </body>
    </html>
  )
}


export default RootLayout
